version: "3.9"

services:
  agent:
    build:
      context: ..
      dockerfile: 06-lab-complete/Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development             # Chuyển về dev để test local dễ hơn
      - AGENT_API_KEY=my-super-secret-key-123
      - JWT_SECRET=local-dev-secret-123
      - APP_NAME=VinBank Agent Production
      - DEBUG=true
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - internal
    ports:
      - "8000:8000"                         # Expose port để test local
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - internal

networks:
  internal:
    driver: bridge
